name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          # GitHub user name to read the contribution graph from
          github_user_name: i-win-again
          # Output file paths
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update snake animation"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"   
